### ISSUE TITLE
City labels crashing into one another

### ISSUE THREAD

**Issue by MarkM2000** [MarkM2000/Final-Project-MAP674#1]
I'm trying to fix the city labels that were crashing into one another for Australia. The way I did these labels is this:

fig, ax = plt.subplots()

base_color = '#f0f0f0'
marker_color = '#448ee4'

australia.plot(ax=ax, color=base_color, zorder=0);
australia_places.plot(ax=ax, color=marker_color, markersize=20, zorder=1);

australia_places.apply(lambda x: ax.annotate(text=x['NAME'],
                                  xy=x.geometry.coords[0],
                                  xytext=(6, 6),
                                  textcoords="offset points"),
                              axis=1);

<img width="632" alt="City labels crash" src="https://github.com/MarkM2000/Final-Project-MAP674/assets/142824282/d79f8286-ed63-4a65-9836-32e18cbda003">

**Comment by rgdonohue** [comment]
Cool, I'll have a look Monday

**Comment by MarkM2000** [comment]
> Cool, I'll have a look Monday

Thank you. I'm looking forward to fixing this bug.

**Comment by MarkM2000** [comment]
Any updates?

**Comment by rgdonohue** [comment]
See Pull Request: https://github.com/MarkM2000/Final-Project-MAP674/pull/3

**Comment by MarkM2000** [comment]
> See Pull Request: #3

I just merged your pull request and it works. The new changes appear on the Notebook.
