### ISSUE TITLE
Pull Leafmap tests out of Final-Project Notebook into new notebook

### ISSUE THREAD

**Issue by rgdonohue** [MarkM2000/Final-Project-MAP674#2]

**Comment by MarkM2000** [comment]
I just created the new Leafmaps page and removed the Leafmaps from the Natural-Gas-Sydney-Suburbs.ipynb (formerly the Final-Project) notebook file.

**Comment by MarkM2000** [comment]
I just created the new Leafmaps page and removed the Leafmaps from the Natural-Gas-Sydney-Suburbs.ipynb (formerly the Final-Project) notebook file.
